import type { DiasporaProfile, EngagementProgram } from "./types";
export const profiles: DiasporaProfile[]=[
{id:"p1",fullName:"Dr. Adaeze Okonkwo",country:"United States",city:"Houston",latitude:29.7604,longitude:-95.3698,sector:"Healthcare",professionTitle:"Cardiothoracic Surgeon",organization:"Texas Medical Center",skills:["clinical leadership","telemedicine","surgical training"],influenceScore:92,investmentCapacityScore:78,strategicValueIndex:88,engagementCategory:"Healthcare Expert",sourceType:"Public professional profile",consentStatus:"Demo consent"},
{id:"p2",fullName:"Chinedu Eze",country:"United States",city:"Atlanta",latitude:33.749,longitude:-84.388,sector:"Technology",professionTitle:"Cloud Security Director",organization:"Fortune 100 Technology Firm",skills:["cybersecurity","cloud architecture","mentorship"],influenceScore:86,investmentCapacityScore:82,strategicValueIndex:87,engagementCategory:"Technology Innovator",sourceType:"Public professional profile",consentStatus:"Demo consent"},
{id:"p3",fullName:"Prof. Ngozi Nwosu",country:"United States",city:"New York",latitude:40.7128,longitude:-74.006,sector:"Academia",professionTitle:"Professor of Public Health",organization:"Columbia University",skills:["epidemiology","grant networks","policy research"],influenceScore:91,investmentCapacityScore:64,strategicValueIndex:84,engagementCategory:"Academic Partner",sourceType:"Conference bio",consentStatus:"Demo consent"},
{id:"p4",fullName:"Tunde Balogun",country:"United States",city:"Dallas",latitude:32.7767,longitude:-96.797,sector:"Finance",professionTitle:"Private Equity Partner",organization:"Diaspora Growth Capital",skills:["infrastructure finance","deal structuring","investor relations"],influenceScore:88,investmentCapacityScore:95,strategicValueIndex:91,engagementCategory:"Investor",sourceType:"Investor directory",consentStatus:"Demo consent"},
{id:"p5",fullName:"Amaka Obi",country:"United Kingdom",city:"London",latitude:51.5072,longitude:-0.1276,sector:"Public Policy",professionTitle:"Senior Policy Adviser",organization:"UK Civil Service",skills:["governance","diaspora policy","stakeholder engagement"],influenceScore:89,investmentCapacityScore:67,strategicValueIndex:83,engagementCategory:"Policy Influencer",sourceType:"Public profile",consentStatus:"Demo consent"},
{id:"p6",fullName:"Kelechi Umeh",country:"United Kingdom",city:"Manchester",latitude:53.4808,longitude:-2.2426,sector:"Engineering",professionTitle:"Rail Systems Engineer",organization:"Northern Transport Alliance",skills:["rail operations","systems safety","project delivery"],influenceScore:76,investmentCapacityScore:73,strategicValueIndex:75,engagementCategory:"Skilled Professional",sourceType:"Professional association",consentStatus:"Demo consent"},
{id:"p7",fullName:"Dr. Ifeoma Adebayo",country:"Canada",city:"Toronto",latitude:43.6532,longitude:-79.3832,sector:"Healthcare",professionTitle:"Health Informatics Lead",organization:"University Health Network",skills:["health data","AI triage","hospital operations"],influenceScore:84,investmentCapacityScore:75,strategicValueIndex:82,engagementCategory:"Healthcare Expert",sourceType:"Public professional profile",consentStatus:"Demo consent"},
{id:"p8",fullName:"Musa Danjuma",country:"Canada",city:"Calgary",latitude:51.0447,longitude:-114.0719,sector:"Engineering",professionTitle:"Energy Transition Engineer",organization:"Prairie Renewables",skills:["renewables","gas systems","project finance"],influenceScore:78,investmentCapacityScore:86,strategicValueIndex:81,engagementCategory:"Skilled Professional",sourceType:"Industry profile",consentStatus:"Demo consent"},
{id:"p9",fullName:"Amina Yusuf",country:"Canada",city:"Ottawa",latitude:45.4215,longitude:-75.6972,sector:"Public Policy",professionTitle:"Multilateral Affairs Specialist",organization:"Global Affairs Network",skills:["trade policy","bilateral relations","program design"],influenceScore:82,investmentCapacityScore:63,strategicValueIndex:78,engagementCategory:"Policy Influencer",sourceType:"Public profile",consentStatus:"Demo consent"},
{id:"p10",fullName:"Emeka Ibe",country:"Germany",city:"Berlin",latitude:52.52,longitude:13.405,sector:"Technology",professionTitle:"AI Product Lead",organization:"European Mobility AI",skills:["machine learning","product strategy","startup scaling"],influenceScore:87,investmentCapacityScore:80,strategicValueIndex:86,engagementCategory:"Technology Innovator",sourceType:"Startup profile",consentStatus:"Demo consent"},
{id:"p11",fullName:"Dr. Bisi Adeyemi",country:"Germany",city:"Munich",latitude:48.1351,longitude:11.582,sector:"Academia",professionTitle:"Robotics Research Scientist",organization:"Technical University of Munich",skills:["robotics","research partnerships","doctoral supervision"],influenceScore:85,investmentCapacityScore:69,strategicValueIndex:82,engagementCategory:"Academic Partner",sourceType:"University bio",consentStatus:"Demo consent"},
{id:"p12",fullName:"Sade Olatunji",country:"South Africa",city:"Johannesburg",latitude:-26.2041,longitude:28.0473,sector:"Creative Economy",professionTitle:"Media Entrepreneur",organization:"AfriStory Studios",skills:["film finance","cultural diplomacy","brand partnerships"],influenceScore:83,investmentCapacityScore:79,strategicValueIndex:80,engagementCategory:"Cultural Ambassador",sourceType:"Media profile",consentStatus:"Demo consent"},
{id:"p13",fullName:"Femi Akinola",country:"South Africa",city:"Cape Town",latitude:-33.9249,longitude:18.4241,sector:"Entrepreneurship",professionTitle:"Fintech Founder",organization:"CapeBridge Payments",skills:["payments","market expansion","venture building"],influenceScore:80,investmentCapacityScore:88,strategicValueIndex:84,engagementCategory:"Investor",sourceType:"Founder profile",consentStatus:"Demo consent"},
{id:"p14",fullName:"Hauwa Bello",country:"UAE",city:"Dubai",latitude:25.2048,longitude:55.2708,sector:"Finance",professionTitle:"Sovereign Wealth Analyst",organization:"Gulf Investment Office",skills:["portfolio strategy","sovereign finance","PPP analysis"],influenceScore:79,investmentCapacityScore:90,strategicValueIndex:84,engagementCategory:"Investor",sourceType:"Public profile",consentStatus:"Demo consent"},
{id:"p15",fullName:"Dr. Osaro Egharevba",country:"UAE",city:"Abu Dhabi",latitude:24.4539,longitude:54.3773,sector:"Healthcare",professionTitle:"Hospital Innovation Director",organization:"Abu Dhabi Health Services",skills:["hospital innovation","clinical quality","medical partnerships"],influenceScore:81,investmentCapacityScore:74,strategicValueIndex:80,engagementCategory:"Healthcare Expert",sourceType:"Conference profile",consentStatus:"Demo consent"}
];
export const programs: EngagementProgram[]=[
{id:"e1",title:"Diaspora Investment Forum",category:"Investor",targetSector:"Finance",targetCountry:"Global",description:"A curated capital mobilisation platform for diaspora investors, Nigerian institutions, and bankable infrastructure opportunities.",expectedImpact:"Pipeline of investable projects, blended finance leads, and measurable diaspora capital commitments."},
{id:"e2",title:"National Advisory Council",category:"Policy Influencer",targetSector:"Public Policy",targetCountry:"Global",description:"A rotating council of high-trust diaspora experts advising federal and state agencies on policy, trade, health, technology, and governance.",expectedImpact:"Faster policy feedback loops and credible global expertise embedded in priority reforms."},
{id:"e3",title:"Talent Return Program",category:"Skilled Professional",targetSector:"Engineering",targetCountry:"Global",description:"Short-term fellowships, relocation pathways, and public-sector secondments for critical skills transfer.",expectedImpact:"Targeted capacity building without requiring permanent relocation for every participant."},
{id:"e4",title:"Remote Mentorship Network",category:"Technology Innovator",targetSector:"Technology",targetCountry:"Global",description:"Mentorship cohorts connecting diaspora specialists with Nigerian startups, universities, hospitals, and agencies.",expectedImpact:"Structured skills transfer, startup support, and professional network expansion."},
{id:"e5",title:"Sector-Based Policy Roundtables",category:"Academic Partner",targetSector:"Academia",targetCountry:"Global",description:"Quarterly evidence sessions for healthcare, technology, academia, finance, and creative economy leaders.",expectedImpact:"Actionable recommendations and partner mapping for national priority sectors."}
];
